joystick_relay:
  ros__parameters:
    priority: True
    turbo:
      linear_forward_min  : 0.01
      linear_forward_max  : 1.0
      linear_backward_min : 0.01
      linear_backward_max : 1.0
      angular_min : 0.01
      angular_max : 0.5
      steps       : 3