twist_mux:
  ros__parameters:
    use_stamped: false
    topics:
      joystick:
        topic   : joy_vel
        timeout : 0.1
        priority: 95
      keyboard: 
        topic   : key_vel
        timeout : 0.1
        priority: 90